import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783701005242 implements MigrationInterface {
    name = 'InitialSchema1783701005242'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "expense_category" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, CONSTRAINT "UQ_33e79cfd65554d411354037e0bf" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "expense" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "amount" float NOT NULL, "category_id" varchar)`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "type" varchar NOT NULL, "quantity" float NOT NULL, "normalized_quantity" float NOT NULL, "adjustment_type" varchar, "reference_type" varchar, "reference_id" varchar, "product_id" varchar, "unit_id" varchar)`);
        await queryRunner.query(`CREATE TABLE "product_brand" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, CONSTRAINT "UQ_aacf9270b7050ef2a350e9a913a" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "product_category" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, CONSTRAINT "UQ_96152d453aaea425b5afde3ae9f" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "cost_price" float NOT NULL, "selling_price" float NOT NULL, "stock_quantity" integer NOT NULL DEFAULT (0), "low_stock_threshold" integer NOT NULL DEFAULT (5), "image_url" varchar, "image_key" varchar, "category_id" varchar, "brand_id" varchar)`);
        await queryRunner.query(`CREATE TABLE "product_unit" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "conversion_factor" float NOT NULL, "is_base_unit" boolean NOT NULL DEFAULT (0), "product_id" varchar NOT NULL, "unit_id" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "unit" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "sale" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "total_amount" float NOT NULL, "total_profit" float NOT NULL, "payment_method" varchar NOT NULL DEFAULT ('cash'))`);
        await queryRunner.query(`CREATE TABLE "sale_item" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "quantity" integer NOT NULL, "selling_price" float NOT NULL, "cost_price" float NOT NULL, "profit" float NOT NULL, "sale_id" varchar, "product_id" varchar)`);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "token_hash" varchar NOT NULL, "expires_at" datetime NOT NULL, "revoked_at" datetime, "user_agent" varchar, "ip" varchar, "user_id" varchar, CONSTRAINT "UQ_f0812282fad2e352cdaf83ef0a9" UNIQUE ("token_hash"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "first_name" varchar NOT NULL, "last_name" varchar NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "temporary_expense" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "amount" float NOT NULL, "category_id" varchar, CONSTRAINT "FK_478b68a9314d8787fb3763a2298" FOREIGN KEY ("category_id") REFERENCES "expense_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_expense"("id", "created_at", "updated_at", "name", "amount", "category_id") SELECT "id", "created_at", "updated_at", "name", "amount", "category_id" FROM "expense"`);
        await queryRunner.query(`DROP TABLE "expense"`);
        await queryRunner.query(`ALTER TABLE "temporary_expense" RENAME TO "expense"`);
        await queryRunner.query(`CREATE TABLE "temporary_inventory" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "type" varchar NOT NULL, "quantity" float NOT NULL, "normalized_quantity" float NOT NULL, "adjustment_type" varchar, "reference_type" varchar, "reference_id" varchar, "product_id" varchar, "unit_id" varchar, CONSTRAINT "FK_732fdb1f76432d65d2c136340dc" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2ab1b938e0b408de0a2dde53b81" FOREIGN KEY ("unit_id") REFERENCES "unit" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_inventory"("id", "created_at", "updated_at", "type", "quantity", "normalized_quantity", "adjustment_type", "reference_type", "reference_id", "product_id", "unit_id") SELECT "id", "created_at", "updated_at", "type", "quantity", "normalized_quantity", "adjustment_type", "reference_type", "reference_id", "product_id", "unit_id" FROM "inventory"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`ALTER TABLE "temporary_inventory" RENAME TO "inventory"`);
        await queryRunner.query(`CREATE TABLE "temporary_product" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "cost_price" float NOT NULL, "selling_price" float NOT NULL, "stock_quantity" integer NOT NULL DEFAULT (0), "low_stock_threshold" integer NOT NULL DEFAULT (5), "image_url" varchar, "image_key" varchar, "category_id" varchar, "brand_id" varchar, CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "product_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2eb5ce4324613b4b457c364f4a2" FOREIGN KEY ("brand_id") REFERENCES "product_brand" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_product"("id", "created_at", "updated_at", "name", "cost_price", "selling_price", "stock_quantity", "low_stock_threshold", "image_url", "image_key", "category_id", "brand_id") SELECT "id", "created_at", "updated_at", "name", "cost_price", "selling_price", "stock_quantity", "low_stock_threshold", "image_url", "image_key", "category_id", "brand_id" FROM "product"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`ALTER TABLE "temporary_product" RENAME TO "product"`);
        await queryRunner.query(`CREATE TABLE "temporary_product_unit" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "conversion_factor" float NOT NULL, "is_base_unit" boolean NOT NULL DEFAULT (0), "product_id" varchar NOT NULL, "unit_id" varchar NOT NULL, CONSTRAINT "FK_09d9c5ec8991fb8d1f506d30a06" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_fe2c478f519e0cc7873f8dfaa07" FOREIGN KEY ("unit_id") REFERENCES "unit" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_product_unit"("id", "created_at", "updated_at", "conversion_factor", "is_base_unit", "product_id", "unit_id") SELECT "id", "created_at", "updated_at", "conversion_factor", "is_base_unit", "product_id", "unit_id" FROM "product_unit"`);
        await queryRunner.query(`DROP TABLE "product_unit"`);
        await queryRunner.query(`ALTER TABLE "temporary_product_unit" RENAME TO "product_unit"`);
        await queryRunner.query(`CREATE TABLE "temporary_sale_item" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "quantity" integer NOT NULL, "selling_price" float NOT NULL, "cost_price" float NOT NULL, "profit" float NOT NULL, "sale_id" varchar, "product_id" varchar, CONSTRAINT "FK_86634f729a5a169e50ab18b98a6" FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_104266e6e0f51e5b33484efa280" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sale_item"("id", "created_at", "updated_at", "quantity", "selling_price", "cost_price", "profit", "sale_id", "product_id") SELECT "id", "created_at", "updated_at", "quantity", "selling_price", "cost_price", "profit", "sale_id", "product_id" FROM "sale_item"`);
        await queryRunner.query(`DROP TABLE "sale_item"`);
        await queryRunner.query(`ALTER TABLE "temporary_sale_item" RENAME TO "sale_item"`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_token" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "token_hash" varchar NOT NULL, "expires_at" datetime NOT NULL, "revoked_at" datetime, "user_agent" varchar, "ip" varchar, "user_id" varchar, CONSTRAINT "UQ_f0812282fad2e352cdaf83ef0a9" UNIQUE ("token_hash"), CONSTRAINT "FK_6bbe63d2fe75e7f0ba1710351d4" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_token"("id", "created_at", "updated_at", "token_hash", "expires_at", "revoked_at", "user_agent", "ip", "user_id") SELECT "id", "created_at", "updated_at", "token_hash", "expires_at", "revoked_at", "user_agent", "ip", "user_id" FROM "refresh_token"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_token" RENAME TO "refresh_token"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_token" RENAME TO "temporary_refresh_token"`);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "token_hash" varchar NOT NULL, "expires_at" datetime NOT NULL, "revoked_at" datetime, "user_agent" varchar, "ip" varchar, "user_id" varchar, CONSTRAINT "UQ_f0812282fad2e352cdaf83ef0a9" UNIQUE ("token_hash"))`);
        await queryRunner.query(`INSERT INTO "refresh_token"("id", "created_at", "updated_at", "token_hash", "expires_at", "revoked_at", "user_agent", "ip", "user_id") SELECT "id", "created_at", "updated_at", "token_hash", "expires_at", "revoked_at", "user_agent", "ip", "user_id" FROM "temporary_refresh_token"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_token"`);
        await queryRunner.query(`ALTER TABLE "sale_item" RENAME TO "temporary_sale_item"`);
        await queryRunner.query(`CREATE TABLE "sale_item" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "quantity" integer NOT NULL, "selling_price" float NOT NULL, "cost_price" float NOT NULL, "profit" float NOT NULL, "sale_id" varchar, "product_id" varchar)`);
        await queryRunner.query(`INSERT INTO "sale_item"("id", "created_at", "updated_at", "quantity", "selling_price", "cost_price", "profit", "sale_id", "product_id") SELECT "id", "created_at", "updated_at", "quantity", "selling_price", "cost_price", "profit", "sale_id", "product_id" FROM "temporary_sale_item"`);
        await queryRunner.query(`DROP TABLE "temporary_sale_item"`);
        await queryRunner.query(`ALTER TABLE "product_unit" RENAME TO "temporary_product_unit"`);
        await queryRunner.query(`CREATE TABLE "product_unit" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "conversion_factor" float NOT NULL, "is_base_unit" boolean NOT NULL DEFAULT (0), "product_id" varchar NOT NULL, "unit_id" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "product_unit"("id", "created_at", "updated_at", "conversion_factor", "is_base_unit", "product_id", "unit_id") SELECT "id", "created_at", "updated_at", "conversion_factor", "is_base_unit", "product_id", "unit_id" FROM "temporary_product_unit"`);
        await queryRunner.query(`DROP TABLE "temporary_product_unit"`);
        await queryRunner.query(`ALTER TABLE "product" RENAME TO "temporary_product"`);
        await queryRunner.query(`CREATE TABLE "product" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "cost_price" float NOT NULL, "selling_price" float NOT NULL, "stock_quantity" integer NOT NULL DEFAULT (0), "low_stock_threshold" integer NOT NULL DEFAULT (5), "image_url" varchar, "image_key" varchar, "category_id" varchar, "brand_id" varchar)`);
        await queryRunner.query(`INSERT INTO "product"("id", "created_at", "updated_at", "name", "cost_price", "selling_price", "stock_quantity", "low_stock_threshold", "image_url", "image_key", "category_id", "brand_id") SELECT "id", "created_at", "updated_at", "name", "cost_price", "selling_price", "stock_quantity", "low_stock_threshold", "image_url", "image_key", "category_id", "brand_id" FROM "temporary_product"`);
        await queryRunner.query(`DROP TABLE "temporary_product"`);
        await queryRunner.query(`ALTER TABLE "inventory" RENAME TO "temporary_inventory"`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "type" varchar NOT NULL, "quantity" float NOT NULL, "normalized_quantity" float NOT NULL, "adjustment_type" varchar, "reference_type" varchar, "reference_id" varchar, "product_id" varchar, "unit_id" varchar)`);
        await queryRunner.query(`INSERT INTO "inventory"("id", "created_at", "updated_at", "type", "quantity", "normalized_quantity", "adjustment_type", "reference_type", "reference_id", "product_id", "unit_id") SELECT "id", "created_at", "updated_at", "type", "quantity", "normalized_quantity", "adjustment_type", "reference_type", "reference_id", "product_id", "unit_id" FROM "temporary_inventory"`);
        await queryRunner.query(`DROP TABLE "temporary_inventory"`);
        await queryRunner.query(`ALTER TABLE "expense" RENAME TO "temporary_expense"`);
        await queryRunner.query(`CREATE TABLE "expense" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "name" varchar NOT NULL, "amount" float NOT NULL, "category_id" varchar)`);
        await queryRunner.query(`INSERT INTO "expense"("id", "created_at", "updated_at", "name", "amount", "category_id") SELECT "id", "created_at", "updated_at", "name", "amount", "category_id" FROM "temporary_expense"`);
        await queryRunner.query(`DROP TABLE "temporary_expense"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
        await queryRunner.query(`DROP TABLE "sale_item"`);
        await queryRunner.query(`DROP TABLE "sale"`);
        await queryRunner.query(`DROP TABLE "unit"`);
        await queryRunner.query(`DROP TABLE "product_unit"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "product_category"`);
        await queryRunner.query(`DROP TABLE "product_brand"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "expense"`);
        await queryRunner.query(`DROP TABLE "expense_category"`);
    }

}
