export type cartActionKey =
    | 'ADD_TO_CART'
    | 'CLEAR_CART'
    | 'REMOVE_FROM_CART'
    | 'INCREASE_QUANTITY_IN_CART'
    | 'DECREASE_QUANTITY_IN_CART'
    | 'CHANGE_ACTIVE_CART'
    | 'ADD_NEW_CART'

export const cartActions: Record<cartActionKey, cartActionKey> = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    DECREASE_QUANTITY_IN_CART: 'DECREASE_QUANTITY_IN_CART',
    INCREASE_QUANTITY_IN_CART: 'INCREASE_QUANTITY_IN_CART',
    CLEAR_CART: 'CLEAR_CART',
    CHANGE_ACTIVE_CART: 'CHANGE_ACTIVE_CART',
    ADD_NEW_CART: 'ADD_NEW_CART'
}
