/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as ProductsAddRouteImport } from './routes/products/add'
import { Route as ExpensesAddRouteImport } from './routes/expenses/add'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products/category/index'
import { Route as ProductsBrandIndexRouteImport } from './routes/products/brand/index'
import { Route as ProductsViewIdRouteImport } from './routes/products/view/$id'
import { Route as ProductsEditIdRouteImport } from './routes/products/edit/$id'
import { Route as ProductsCategoryAddRouteImport } from './routes/products/category/add'
import { Route as ProductsBrandAddRouteImport } from './routes/products/brand/add'
import { Route as ExpensesViewIdRouteImport } from './routes/expenses/view/$id'
import { Route as ExpensesEditIdRouteImport } from './routes/expenses/edit/$id'
import { Route as ProductsCategoryViewIdRouteImport } from './routes/products/category/view/$id'
import { Route as ProductsCategoryEditIdRouteImport } from './routes/products/category/edit/$id'
import { Route as ProductsBrandViewIdRouteImport } from './routes/products/brand/view/$id'
import { Route as ProductsBrandEditIdRouteImport } from './routes/products/brand/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAddRoute = ProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesAddRoute = ExpensesAddRouteImport.update({
  id: '/expenses/add',
  path: '/expenses/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/category/',
  path: '/products/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBrandIndexRoute = ProductsBrandIndexRouteImport.update({
  id: '/products/brand/',
  path: '/products/brand/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsViewIdRoute = ProductsViewIdRouteImport.update({
  id: '/products/view/$id',
  path: '/products/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEditIdRoute = ProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryAddRoute = ProductsCategoryAddRouteImport.update({
  id: '/products/category/add',
  path: '/products/category/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBrandAddRoute = ProductsBrandAddRouteImport.update({
  id: '/products/brand/add',
  path: '/products/brand/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesViewIdRoute = ExpensesViewIdRouteImport.update({
  id: '/expenses/view/$id',
  path: '/expenses/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesEditIdRoute = ExpensesEditIdRouteImport.update({
  id: '/expenses/edit/$id',
  path: '/expenses/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryViewIdRoute = ProductsCategoryViewIdRouteImport.update({
  id: '/products/category/view/$id',
  path: '/products/category/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryEditIdRoute = ProductsCategoryEditIdRouteImport.update({
  id: '/products/category/edit/$id',
  path: '/products/category/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBrandViewIdRoute = ProductsBrandViewIdRouteImport.update({
  id: '/products/brand/view/$id',
  path: '/products/brand/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBrandEditIdRoute = ProductsBrandEditIdRouteImport.update({
  id: '/products/brand/edit/$id',
  path: '/products/brand/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses/add': typeof ExpensesAddRoute
  '/products/add': typeof ProductsAddRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/expenses/edit/$id': typeof ExpensesEditIdRoute
  '/expenses/view/$id': typeof ExpensesViewIdRoute
  '/products/brand/add': typeof ProductsBrandAddRoute
  '/products/category/add': typeof ProductsCategoryAddRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/products/view/$id': typeof ProductsViewIdRoute
  '/products/brand/': typeof ProductsBrandIndexRoute
  '/products/category/': typeof ProductsCategoryIndexRoute
  '/products/brand/edit/$id': typeof ProductsBrandEditIdRoute
  '/products/brand/view/$id': typeof ProductsBrandViewIdRoute
  '/products/category/edit/$id': typeof ProductsCategoryEditIdRoute
  '/products/category/view/$id': typeof ProductsCategoryViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses/add': typeof ExpensesAddRoute
  '/products/add': typeof ProductsAddRoute
  '/expenses': typeof ExpensesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/expenses/edit/$id': typeof ExpensesEditIdRoute
  '/expenses/view/$id': typeof ExpensesViewIdRoute
  '/products/brand/add': typeof ProductsBrandAddRoute
  '/products/category/add': typeof ProductsCategoryAddRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/products/view/$id': typeof ProductsViewIdRoute
  '/products/brand': typeof ProductsBrandIndexRoute
  '/products/category': typeof ProductsCategoryIndexRoute
  '/products/brand/edit/$id': typeof ProductsBrandEditIdRoute
  '/products/brand/view/$id': typeof ProductsBrandViewIdRoute
  '/products/category/edit/$id': typeof ProductsCategoryEditIdRoute
  '/products/category/view/$id': typeof ProductsCategoryViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses/add': typeof ExpensesAddRoute
  '/products/add': typeof ProductsAddRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/expenses/edit/$id': typeof ExpensesEditIdRoute
  '/expenses/view/$id': typeof ExpensesViewIdRoute
  '/products/brand/add': typeof ProductsBrandAddRoute
  '/products/category/add': typeof ProductsCategoryAddRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/products/view/$id': typeof ProductsViewIdRoute
  '/products/brand/': typeof ProductsBrandIndexRoute
  '/products/category/': typeof ProductsCategoryIndexRoute
  '/products/brand/edit/$id': typeof ProductsBrandEditIdRoute
  '/products/brand/view/$id': typeof ProductsBrandViewIdRoute
  '/products/category/edit/$id': typeof ProductsCategoryEditIdRoute
  '/products/category/view/$id': typeof ProductsCategoryViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses/add'
    | '/products/add'
    | '/expenses/'
    | '/inventory/'
    | '/products/'
    | '/sales/'
    | '/expenses/edit/$id'
    | '/expenses/view/$id'
    | '/products/brand/add'
    | '/products/category/add'
    | '/products/edit/$id'
    | '/products/view/$id'
    | '/products/brand/'
    | '/products/category/'
    | '/products/brand/edit/$id'
    | '/products/brand/view/$id'
    | '/products/category/edit/$id'
    | '/products/category/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses/add'
    | '/products/add'
    | '/expenses'
    | '/inventory'
    | '/products'
    | '/sales'
    | '/expenses/edit/$id'
    | '/expenses/view/$id'
    | '/products/brand/add'
    | '/products/category/add'
    | '/products/edit/$id'
    | '/products/view/$id'
    | '/products/brand'
    | '/products/category'
    | '/products/brand/edit/$id'
    | '/products/brand/view/$id'
    | '/products/category/edit/$id'
    | '/products/category/view/$id'
  id:
    | '__root__'
    | '/'
    | '/expenses/add'
    | '/products/add'
    | '/expenses/'
    | '/inventory/'
    | '/products/'
    | '/sales/'
    | '/expenses/edit/$id'
    | '/expenses/view/$id'
    | '/products/brand/add'
    | '/products/category/add'
    | '/products/edit/$id'
    | '/products/view/$id'
    | '/products/brand/'
    | '/products/category/'
    | '/products/brand/edit/$id'
    | '/products/brand/view/$id'
    | '/products/category/edit/$id'
    | '/products/category/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesAddRoute: typeof ExpensesAddRoute
  ProductsAddRoute: typeof ProductsAddRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  ExpensesEditIdRoute: typeof ExpensesEditIdRoute
  ExpensesViewIdRoute: typeof ExpensesViewIdRoute
  ProductsBrandAddRoute: typeof ProductsBrandAddRoute
  ProductsCategoryAddRoute: typeof ProductsCategoryAddRoute
  ProductsEditIdRoute: typeof ProductsEditIdRoute
  ProductsViewIdRoute: typeof ProductsViewIdRoute
  ProductsBrandIndexRoute: typeof ProductsBrandIndexRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
  ProductsBrandEditIdRoute: typeof ProductsBrandEditIdRoute
  ProductsBrandViewIdRoute: typeof ProductsBrandViewIdRoute
  ProductsCategoryEditIdRoute: typeof ProductsCategoryEditIdRoute
  ProductsCategoryViewIdRoute: typeof ProductsCategoryViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/add': {
      id: '/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/add': {
      id: '/expenses/add'
      path: '/expenses/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof ExpensesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/': {
      id: '/products/category/'
      path: '/products/category'
      fullPath: '/products/category/'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/brand/': {
      id: '/products/brand/'
      path: '/products/brand'
      fullPath: '/products/brand/'
      preLoaderRoute: typeof ProductsBrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/view/$id': {
      id: '/products/view/$id'
      path: '/products/view/$id'
      fullPath: '/products/view/$id'
      preLoaderRoute: typeof ProductsViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/edit/$id': {
      id: '/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof ProductsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/add': {
      id: '/products/category/add'
      path: '/products/category/add'
      fullPath: '/products/category/add'
      preLoaderRoute: typeof ProductsCategoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/brand/add': {
      id: '/products/brand/add'
      path: '/products/brand/add'
      fullPath: '/products/brand/add'
      preLoaderRoute: typeof ProductsBrandAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/view/$id': {
      id: '/expenses/view/$id'
      path: '/expenses/view/$id'
      fullPath: '/expenses/view/$id'
      preLoaderRoute: typeof ExpensesViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/edit/$id': {
      id: '/expenses/edit/$id'
      path: '/expenses/edit/$id'
      fullPath: '/expenses/edit/$id'
      preLoaderRoute: typeof ExpensesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/view/$id': {
      id: '/products/category/view/$id'
      path: '/products/category/view/$id'
      fullPath: '/products/category/view/$id'
      preLoaderRoute: typeof ProductsCategoryViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/edit/$id': {
      id: '/products/category/edit/$id'
      path: '/products/category/edit/$id'
      fullPath: '/products/category/edit/$id'
      preLoaderRoute: typeof ProductsCategoryEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/brand/view/$id': {
      id: '/products/brand/view/$id'
      path: '/products/brand/view/$id'
      fullPath: '/products/brand/view/$id'
      preLoaderRoute: typeof ProductsBrandViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/brand/edit/$id': {
      id: '/products/brand/edit/$id'
      path: '/products/brand/edit/$id'
      fullPath: '/products/brand/edit/$id'
      preLoaderRoute: typeof ProductsBrandEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesAddRoute: ExpensesAddRoute,
  ProductsAddRoute: ProductsAddRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  ExpensesEditIdRoute: ExpensesEditIdRoute,
  ExpensesViewIdRoute: ExpensesViewIdRoute,
  ProductsBrandAddRoute: ProductsBrandAddRoute,
  ProductsCategoryAddRoute: ProductsCategoryAddRoute,
  ProductsEditIdRoute: ProductsEditIdRoute,
  ProductsViewIdRoute: ProductsViewIdRoute,
  ProductsBrandIndexRoute: ProductsBrandIndexRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
  ProductsBrandEditIdRoute: ProductsBrandEditIdRoute,
  ProductsBrandViewIdRoute: ProductsBrandViewIdRoute,
  ProductsCategoryEditIdRoute: ProductsCategoryEditIdRoute,
  ProductsCategoryViewIdRoute: ProductsCategoryViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
