/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/_account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as OfflineAuthRouteImport } from './routes/_offline-auth'
import { Route as AccountRecoverRouteImport } from './routes/_account/recover'
import { Route as AccountSetRecoveryQuestionsRouteImport } from './routes/_account/set-recovery-questions'
import { Route as AuthLocalAccessRouteImport } from './routes/_auth/local-access'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as OfflineAuthVerifyAccessRouteImport } from './routes/_offline-auth/verify-access'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardExpensesIndexRouteImport } from './routes/_dashboard/expenses/index'
import { Route as DashboardExpensesAddRouteImport } from './routes/_dashboard/expenses/add'
import { Route as DashboardInventoryIndexRouteImport } from './routes/_dashboard/inventory/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardProductsAddRouteImport } from './routes/_dashboard/products/add'
import { Route as DashboardExpensesEditIdRouteImport } from './routes/_dashboard/expenses/edit/$id'
import { Route as DashboardExpensesViewIdRouteImport } from './routes/_dashboard/expenses/view/$id'
import { Route as DashboardProductsBrandIndexRouteImport } from './routes/_dashboard/products/brand/index'
import { Route as DashboardProductsBrandAddRouteImport } from './routes/_dashboard/products/brand/add'
import { Route as DashboardProductsCategoryIndexRouteImport } from './routes/_dashboard/products/category/index'
import { Route as DashboardProductsCategoryAddRouteImport } from './routes/_dashboard/products/category/add'
import { Route as DashboardProductsEditIdRouteImport } from './routes/_dashboard/products/edit/$id'
import { Route as DashboardProductsViewIdRouteImport } from './routes/_dashboard/products/view/$id'
import { Route as DashboardProductsBrandEditIdRouteImport } from './routes/_dashboard/products/brand/edit/$id'
import { Route as DashboardProductsBrandViewIdRouteImport } from './routes/_dashboard/products/brand/view/$id'
import { Route as DashboardProductsCategoryEditIdRouteImport } from './routes/_dashboard/products/category/edit/$id'
import { Route as DashboardProductsCategoryViewIdRouteImport } from './routes/_dashboard/products/category/view/$id'

const AccountRoute = AccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineAuthRoute = OfflineAuthRouteImport.update({
  id: '/_offline-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRecoverRoute = AccountRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSetRecoveryQuestionsRoute =
  AccountSetRecoveryQuestionsRouteImport.update({
    id: '/set-recovery-questions',
    path: '/set-recovery-questions',
    getParentRoute: () => AccountRoute,
  } as any)
const AuthLocalAccessRoute = AuthLocalAccessRouteImport.update({
  id: '/local-access',
  path: '/local-access',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OfflineAuthVerifyAccessRoute = OfflineAuthVerifyAccessRouteImport.update({
  id: '/verify-access',
  path: '/verify-access',
  getParentRoute: () => OfflineAuthRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesIndexRoute = DashboardExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesAddRoute = DashboardExpensesAddRouteImport.update({
  id: '/expenses/add',
  path: '/expenses/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsAddRoute = DashboardProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesEditIdRoute = DashboardExpensesEditIdRouteImport.update({
  id: '/expenses/edit/$id',
  path: '/expenses/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesViewIdRoute = DashboardExpensesViewIdRouteImport.update({
  id: '/expenses/view/$id',
  path: '/expenses/view/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsBrandIndexRoute =
  DashboardProductsBrandIndexRouteImport.update({
    id: '/products/brand/',
    path: '/products/brand/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsBrandAddRoute =
  DashboardProductsBrandAddRouteImport.update({
    id: '/products/brand/add',
    path: '/products/brand/add',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsCategoryIndexRoute =
  DashboardProductsCategoryIndexRouteImport.update({
    id: '/products/category/',
    path: '/products/category/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsCategoryAddRoute =
  DashboardProductsCategoryAddRouteImport.update({
    id: '/products/category/add',
    path: '/products/category/add',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsEditIdRoute = DashboardProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsViewIdRoute = DashboardProductsViewIdRouteImport.update({
  id: '/products/view/$id',
  path: '/products/view/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsBrandEditIdRoute =
  DashboardProductsBrandEditIdRouteImport.update({
    id: '/products/brand/edit/$id',
    path: '/products/brand/edit/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsBrandViewIdRoute =
  DashboardProductsBrandViewIdRouteImport.update({
    id: '/products/brand/view/$id',
    path: '/products/brand/view/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsCategoryEditIdRoute =
  DashboardProductsCategoryEditIdRouteImport.update({
    id: '/products/category/edit/$id',
    path: '/products/category/edit/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsCategoryViewIdRoute =
  DashboardProductsCategoryViewIdRouteImport.update({
    id: '/products/category/view/$id',
    path: '/products/category/view/$id',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/recover': typeof AccountRecoverRoute
  '/set-recovery-questions': typeof AccountSetRecoveryQuestionsRoute
  '/local-access': typeof AuthLocalAccessRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-access': typeof OfflineAuthVerifyAccessRoute
  '/expenses/add': typeof DashboardExpensesAddRoute
  '/products/add': typeof DashboardProductsAddRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/expenses/': typeof DashboardExpensesIndexRoute
  '/inventory/': typeof DashboardInventoryIndexRoute
  '/products/': typeof DashboardProductsIndexRoute
  '/expenses/edit/$id': typeof DashboardExpensesEditIdRoute
  '/expenses/view/$id': typeof DashboardExpensesViewIdRoute
  '/products/brand/add': typeof DashboardProductsBrandAddRoute
  '/products/category/add': typeof DashboardProductsCategoryAddRoute
  '/products/edit/$id': typeof DashboardProductsEditIdRoute
  '/products/view/$id': typeof DashboardProductsViewIdRoute
  '/products/brand/': typeof DashboardProductsBrandIndexRoute
  '/products/category/': typeof DashboardProductsCategoryIndexRoute
  '/products/brand/edit/$id': typeof DashboardProductsBrandEditIdRoute
  '/products/brand/view/$id': typeof DashboardProductsBrandViewIdRoute
  '/products/category/edit/$id': typeof DashboardProductsCategoryEditIdRoute
  '/products/category/view/$id': typeof DashboardProductsCategoryViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/recover': typeof AccountRecoverRoute
  '/set-recovery-questions': typeof AccountSetRecoveryQuestionsRoute
  '/local-access': typeof AuthLocalAccessRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-access': typeof OfflineAuthVerifyAccessRoute
  '/expenses/add': typeof DashboardExpensesAddRoute
  '/products/add': typeof DashboardProductsAddRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/expenses': typeof DashboardExpensesIndexRoute
  '/inventory': typeof DashboardInventoryIndexRoute
  '/products': typeof DashboardProductsIndexRoute
  '/expenses/edit/$id': typeof DashboardExpensesEditIdRoute
  '/expenses/view/$id': typeof DashboardExpensesViewIdRoute
  '/products/brand/add': typeof DashboardProductsBrandAddRoute
  '/products/category/add': typeof DashboardProductsCategoryAddRoute
  '/products/edit/$id': typeof DashboardProductsEditIdRoute
  '/products/view/$id': typeof DashboardProductsViewIdRoute
  '/products/brand': typeof DashboardProductsBrandIndexRoute
  '/products/category': typeof DashboardProductsCategoryIndexRoute
  '/products/brand/edit/$id': typeof DashboardProductsBrandEditIdRoute
  '/products/brand/view/$id': typeof DashboardProductsBrandViewIdRoute
  '/products/category/edit/$id': typeof DashboardProductsCategoryEditIdRoute
  '/products/category/view/$id': typeof DashboardProductsCategoryViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_offline-auth': typeof OfflineAuthRouteWithChildren
  '/_account/recover': typeof AccountRecoverRoute
  '/_account/set-recovery-questions': typeof AccountSetRecoveryQuestionsRoute
  '/_auth/local-access': typeof AuthLocalAccessRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_offline-auth/verify-access': typeof OfflineAuthVerifyAccessRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/expenses/add': typeof DashboardExpensesAddRoute
  '/_dashboard/products/add': typeof DashboardProductsAddRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/expenses/': typeof DashboardExpensesIndexRoute
  '/_dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
  '/_dashboard/expenses/edit/$id': typeof DashboardExpensesEditIdRoute
  '/_dashboard/expenses/view/$id': typeof DashboardExpensesViewIdRoute
  '/_dashboard/products/brand/add': typeof DashboardProductsBrandAddRoute
  '/_dashboard/products/category/add': typeof DashboardProductsCategoryAddRoute
  '/_dashboard/products/edit/$id': typeof DashboardProductsEditIdRoute
  '/_dashboard/products/view/$id': typeof DashboardProductsViewIdRoute
  '/_dashboard/products/brand/': typeof DashboardProductsBrandIndexRoute
  '/_dashboard/products/category/': typeof DashboardProductsCategoryIndexRoute
  '/_dashboard/products/brand/edit/$id': typeof DashboardProductsBrandEditIdRoute
  '/_dashboard/products/brand/view/$id': typeof DashboardProductsBrandViewIdRoute
  '/_dashboard/products/category/edit/$id': typeof DashboardProductsCategoryEditIdRoute
  '/_dashboard/products/category/view/$id': typeof DashboardProductsCategoryViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recover'
    | '/set-recovery-questions'
    | '/local-access'
    | '/login'
    | '/register'
    | '/verify-access'
    | '/expenses/add'
    | '/products/add'
    | '/dashboard/'
    | '/expenses/'
    | '/inventory/'
    | '/products/'
    | '/expenses/edit/$id'
    | '/expenses/view/$id'
    | '/products/brand/add'
    | '/products/category/add'
    | '/products/edit/$id'
    | '/products/view/$id'
    | '/products/brand/'
    | '/products/category/'
    | '/products/brand/edit/$id'
    | '/products/brand/view/$id'
    | '/products/category/edit/$id'
    | '/products/category/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recover'
    | '/set-recovery-questions'
    | '/local-access'
    | '/login'
    | '/register'
    | '/verify-access'
    | '/expenses/add'
    | '/products/add'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/products'
    | '/expenses/edit/$id'
    | '/expenses/view/$id'
    | '/products/brand/add'
    | '/products/category/add'
    | '/products/edit/$id'
    | '/products/view/$id'
    | '/products/brand'
    | '/products/category'
    | '/products/brand/edit/$id'
    | '/products/brand/view/$id'
    | '/products/category/edit/$id'
    | '/products/category/view/$id'
  id:
    | '__root__'
    | '/_account'
    | '/_auth'
    | '/_dashboard'
    | '/_offline-auth'
    | '/_account/recover'
    | '/_account/set-recovery-questions'
    | '/_auth/local-access'
    | '/_auth/login'
    | '/_auth/register'
    | '/_offline-auth/verify-access'
    | '/_dashboard/'
    | '/_dashboard/expenses/add'
    | '/_dashboard/products/add'
    | '/_dashboard/dashboard/'
    | '/_dashboard/expenses/'
    | '/_dashboard/inventory/'
    | '/_dashboard/products/'
    | '/_dashboard/expenses/edit/$id'
    | '/_dashboard/expenses/view/$id'
    | '/_dashboard/products/brand/add'
    | '/_dashboard/products/category/add'
    | '/_dashboard/products/edit/$id'
    | '/_dashboard/products/view/$id'
    | '/_dashboard/products/brand/'
    | '/_dashboard/products/category/'
    | '/_dashboard/products/brand/edit/$id'
    | '/_dashboard/products/brand/view/$id'
    | '/_dashboard/products/category/edit/$id'
    | '/_dashboard/products/category/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  OfflineAuthRoute: typeof OfflineAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_offline-auth': {
      id: '/_offline-auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OfflineAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/recover': {
      id: '/_account/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AccountRecoverRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/set-recovery-questions': {
      id: '/_account/set-recovery-questions'
      path: '/set-recovery-questions'
      fullPath: '/set-recovery-questions'
      preLoaderRoute: typeof AccountSetRecoveryQuestionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_auth/local-access': {
      id: '/_auth/local-access'
      path: '/local-access'
      fullPath: '/local-access'
      preLoaderRoute: typeof AuthLocalAccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_offline-auth/verify-access': {
      id: '/_offline-auth/verify-access'
      path: '/verify-access'
      fullPath: '/verify-access'
      preLoaderRoute: typeof OfflineAuthVerifyAccessRouteImport
      parentRoute: typeof OfflineAuthRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/expenses/': {
      id: '/_dashboard/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof DashboardExpensesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/expenses/add': {
      id: '/_dashboard/expenses/add'
      path: '/expenses/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof DashboardExpensesAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventory/': {
      id: '/_dashboard/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/add': {
      id: '/_dashboard/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof DashboardProductsAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/expenses/edit/$id': {
      id: '/_dashboard/expenses/edit/$id'
      path: '/expenses/edit/$id'
      fullPath: '/expenses/edit/$id'
      preLoaderRoute: typeof DashboardExpensesEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/expenses/view/$id': {
      id: '/_dashboard/expenses/view/$id'
      path: '/expenses/view/$id'
      fullPath: '/expenses/view/$id'
      preLoaderRoute: typeof DashboardExpensesViewIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/brand/': {
      id: '/_dashboard/products/brand/'
      path: '/products/brand'
      fullPath: '/products/brand/'
      preLoaderRoute: typeof DashboardProductsBrandIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/brand/add': {
      id: '/_dashboard/products/brand/add'
      path: '/products/brand/add'
      fullPath: '/products/brand/add'
      preLoaderRoute: typeof DashboardProductsBrandAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/category/': {
      id: '/_dashboard/products/category/'
      path: '/products/category'
      fullPath: '/products/category/'
      preLoaderRoute: typeof DashboardProductsCategoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/category/add': {
      id: '/_dashboard/products/category/add'
      path: '/products/category/add'
      fullPath: '/products/category/add'
      preLoaderRoute: typeof DashboardProductsCategoryAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/edit/$id': {
      id: '/_dashboard/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof DashboardProductsEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/view/$id': {
      id: '/_dashboard/products/view/$id'
      path: '/products/view/$id'
      fullPath: '/products/view/$id'
      preLoaderRoute: typeof DashboardProductsViewIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/brand/edit/$id': {
      id: '/_dashboard/products/brand/edit/$id'
      path: '/products/brand/edit/$id'
      fullPath: '/products/brand/edit/$id'
      preLoaderRoute: typeof DashboardProductsBrandEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/brand/view/$id': {
      id: '/_dashboard/products/brand/view/$id'
      path: '/products/brand/view/$id'
      fullPath: '/products/brand/view/$id'
      preLoaderRoute: typeof DashboardProductsBrandViewIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/category/edit/$id': {
      id: '/_dashboard/products/category/edit/$id'
      path: '/products/category/edit/$id'
      fullPath: '/products/category/edit/$id'
      preLoaderRoute: typeof DashboardProductsCategoryEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/category/view/$id': {
      id: '/_dashboard/products/category/view/$id'
      path: '/products/category/view/$id'
      fullPath: '/products/category/view/$id'
      preLoaderRoute: typeof DashboardProductsCategoryViewIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AccountRouteChildren {
  AccountRecoverRoute: typeof AccountRecoverRoute
  AccountSetRecoveryQuestionsRoute: typeof AccountSetRecoveryQuestionsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountRecoverRoute: AccountRecoverRoute,
  AccountSetRecoveryQuestionsRoute: AccountSetRecoveryQuestionsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AuthRouteChildren {
  AuthLocalAccessRoute: typeof AuthLocalAccessRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLocalAccessRoute: AuthLocalAccessRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExpensesAddRoute: typeof DashboardExpensesAddRoute
  DashboardProductsAddRoute: typeof DashboardProductsAddRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardExpensesIndexRoute: typeof DashboardExpensesIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardExpensesEditIdRoute: typeof DashboardExpensesEditIdRoute
  DashboardExpensesViewIdRoute: typeof DashboardExpensesViewIdRoute
  DashboardProductsBrandAddRoute: typeof DashboardProductsBrandAddRoute
  DashboardProductsCategoryAddRoute: typeof DashboardProductsCategoryAddRoute
  DashboardProductsEditIdRoute: typeof DashboardProductsEditIdRoute
  DashboardProductsViewIdRoute: typeof DashboardProductsViewIdRoute
  DashboardProductsBrandIndexRoute: typeof DashboardProductsBrandIndexRoute
  DashboardProductsCategoryIndexRoute: typeof DashboardProductsCategoryIndexRoute
  DashboardProductsBrandEditIdRoute: typeof DashboardProductsBrandEditIdRoute
  DashboardProductsBrandViewIdRoute: typeof DashboardProductsBrandViewIdRoute
  DashboardProductsCategoryEditIdRoute: typeof DashboardProductsCategoryEditIdRoute
  DashboardProductsCategoryViewIdRoute: typeof DashboardProductsCategoryViewIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExpensesAddRoute: DashboardExpensesAddRoute,
  DashboardProductsAddRoute: DashboardProductsAddRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardExpensesIndexRoute: DashboardExpensesIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardExpensesEditIdRoute: DashboardExpensesEditIdRoute,
  DashboardExpensesViewIdRoute: DashboardExpensesViewIdRoute,
  DashboardProductsBrandAddRoute: DashboardProductsBrandAddRoute,
  DashboardProductsCategoryAddRoute: DashboardProductsCategoryAddRoute,
  DashboardProductsEditIdRoute: DashboardProductsEditIdRoute,
  DashboardProductsViewIdRoute: DashboardProductsViewIdRoute,
  DashboardProductsBrandIndexRoute: DashboardProductsBrandIndexRoute,
  DashboardProductsCategoryIndexRoute: DashboardProductsCategoryIndexRoute,
  DashboardProductsBrandEditIdRoute: DashboardProductsBrandEditIdRoute,
  DashboardProductsBrandViewIdRoute: DashboardProductsBrandViewIdRoute,
  DashboardProductsCategoryEditIdRoute: DashboardProductsCategoryEditIdRoute,
  DashboardProductsCategoryViewIdRoute: DashboardProductsCategoryViewIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OfflineAuthRouteChildren {
  OfflineAuthVerifyAccessRoute: typeof OfflineAuthVerifyAccessRoute
}

const OfflineAuthRouteChildren: OfflineAuthRouteChildren = {
  OfflineAuthVerifyAccessRoute: OfflineAuthVerifyAccessRoute,
}

const OfflineAuthRouteWithChildren = OfflineAuthRoute._addFileChildren(
  OfflineAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OfflineAuthRoute: OfflineAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
