
services:
  dukatiq-postgres:
    image: postgres:17
    container_name: dukatiq-postgres-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dukatiq_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  dukatiq-redis:
    image: redis:7.2
    container_name: dukatiq-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - dukatiq_redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  dukatiq_postgres_data:
  dukatiq_redis_data: