import { StatusCodes } from 'http-status-codes'

export class AppError extends Error {
    constructor({
        message,
        code = 'APP_ERROR',
        status = StatusCodes.BAD_REQUEST,
        meta = {},
    }) {
        super(message)
        this.name = 'AppError'
        this.code = code
        this.status = status
        this.statusCode = status
        this.meta = meta
    }
}

export const ERROR_CODES = {
    AUTH: {
        ACCOUNT_ALREADY_EXISTS: 'AUTH_ACCOUNT_ALREADY_EXISTS',
        INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
        INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
    },
    EXPENSE: {
        NOT_FOUND: 'EXPENSE_NOT_FOUND',
        UPDATE_FAILED: 'EXPENSE_UPDATE_FAILED',
        DELETE_FAILED: 'EXPENSE_DELETE_FAILED',
    },
    EXPENSE_CATEGORY: {
        NOT_FOUND: 'EXPENSE_CATEGORY_NOT_FOUND',
        ALREADY_EXISTS: 'EXPENSE_CATEGORY_ALREADY_EXISTS',
        UPDATE_FAILED: 'EXPENSE_CATEGORY_UPDATE_FAILED',
        DELETE_FAILED: 'EXPENSE_CATEGORY_DELETE_FAILED',
    },
    FILE: {
        NO_FILE_PROVIDED: 'FILE_NO_FILE_PROVIDED',
        EMPTY_FILE_BUFFER: 'FILE_EMPTY_FILE_BUFFER',
        INVALID_UPLOAD: 'FILE_INVALID_UPLOAD',
        KEY_REQUIRED: 'FILE_KEY_REQUIRED',
        DELETE_FAILED: 'FILE_DELETE_FAILED',
        SIGN_URL_FAILED: 'FILE_SIGN_URL_FAILED',
    },
    INVENTORY: {
        NOT_FOUND: 'INVENTORY_NOT_FOUND',
        UNIT_NOT_FOUND: 'INVENTORY_UNIT_NOT_FOUND',
        INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
        CREATE_FAILED: 'INVENTORY_CREATE_FAILED',
        DELETE_FAILED: 'INVENTORY_DELETE_FAILED',
    },
    PRODUCT: {
        NOT_FOUND: 'PRODUCT_NOT_FOUND',
        ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
        UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',
        DELETE_FAILED: 'PRODUCT_DELETE_FAILED',
    },
    PRODUCT_CATEGORY: {
        NOT_FOUND: 'PRODUCT_CATEGORY_NOT_FOUND',
        ALREADY_EXISTS: 'PRODUCT_CATEGORY_ALREADY_EXISTS',
        UPDATE_FAILED: 'PRODUCT_CATEGORY_UPDATE_FAILED',
        DELETE_FAILED: 'PRODUCT_CATEGORY_DELETE_FAILED',
    },
    PRODUCT_UNIT: {
        NOT_FOUND: 'PRODUCT_UNIT_NOT_FOUND',
        BASE_REQUIRED: 'PRODUCT_UNIT_BASE_REQUIRED',
        CANNOT_DELETE_BASE: 'PRODUCT_UNIT_CANNOT_DELETE_BASE',
        ONLY_BASE_UNIT: 'PRODUCT_UNIT_ONLY_BASE_UNIT',
        NOT_CONFIGURED: 'PRODUCT_UNIT_NOT_CONFIGURED',
        ALREADY_EXISTS: 'PRODUCT_UNIT_ALREADY_EXISTS',
        UPDATE_FAILED: 'PRODUCT_UNIT_UPDATE_FAILED',
        DELETE_FAILED: 'PRODUCT_UNIT_DELETE_FAILED',
    },
    UNIT: {
        NOT_FOUND: 'UNIT_NOT_FOUND',
        ALREADY_EXISTS: 'UNIT_ALREADY_EXISTS',
        DELETE_FAILED: 'UNIT_DELETE_FAILED',
    },
}
