import type { WorkOrder } from "./types";

// Swap this file for `api.ts` (real fetch/TanStack Query) once the backend is ready.
// Every consumer of this data (table, board, calendar) stays the same.
export const mockWorkOrders: WorkOrder[] = [
  {
    id: "1",
    woNumber: "8391",
    title: "HVAC Routine Service 2",
    assignee: { name: "Kathryn Murphy" },
    startDate: "8 Mar, 25",
    dueDate: "Today",
    category: "Preventative",
    priority: "low",
    location: "Suite B",
    asset: "Fan Assembly - TRA...",
  },
  {
    id: "2",
    woNumber: "8391",
    title: "HVAC Routine Service",
    assignee: { name: "Leslie Alexander" },
    startDate: "9 Mar, 25",
    dueDate: "Today",
    category: "Preventative",
    priority: "medium",
    location: "Suite B",
    asset: "Fan Assembly - TRA...",
  },
  {
    id: "3",
    woNumber: "8391",
    title: "HVAC Preventive Care",
    assignee: { name: "Theresa Webb" },
    startDate: "8 Mar, 25",
    dueDate: "Tomorrow",
    category: "Meter Reading",
    priority: "low",
    location: "Suite A",
    asset: "Fan Assembly - TRA...",
  },
  {
    id: "4",
    woNumber: "8391",
    title: "HVAC Monthly Inspection",
    assignee: { name: "Annette Black" },
    startDate: "10 Mar, 25",
    dueDate: "10 Apr, 25",
    category: "Preventative",
    priority: "high",
    location: "Suite B",
    asset: "Fan Assembly - TRA...",
  },
  {
    id: "5",
    woNumber: "8391",
    title: "HVAC Monthly Tune-Up",
    assignee: { name: "Bessie Cooper" },
    startDate: "11 Mar, 25",
    dueDate: "22 Mar, 25",
    category: "Meter Reading",
    priority: "low",
    location: "Suite A",
    asset: "Fan Assembly - TRA...",
  },
  
];
