name: Server Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server   # 👈 KEY FIX

    env:
      NODE_ENV: test
      COOKIE_SECRET: test_cookie_secret
      DB_PATH: ":memory:"
      JWT_SECRET: test_jwt_secret


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test